language: python
python: 3.6
dist: trusty
sudo: false
group: beta

script:
  - ./checkjson.py && ./coverage.sh
  - ./tidy-json.sh && git diff --exit-code
  - ./dupcheck.py
  - ./dupassign.py
  - ./DiceLen.py
  - ./ItemLen.py
  - ./ItemDescLen.py
  - ./StoryBTNFont.py
  - ./StoryFont.py
  - ./ChipFont.py
  - ./ChipDescShort.py
  - ./ChipDescLong.py
  - ./DiceFont.py
  - ./ItemFont.py
  - ./ItemDescFont.py
