language: python
python: 3.6
dist: trusty
sudo: false
group: beta

script:
  - ./_py/checkjson.py && ./_sh/coverage.sh
  - ./_sh/tidy-json.sh json && git diff --exit-code
  - ./_py/dupcheck.py
  - ./_py/dupassign.py
  - ./_py/DiceLen.py
  - ./_py/ItemLen.py
  - ./_py/ItemDescLen.py
  - ./_py/StoryBTNFont.py
  - ./_py/StoryFont.py
  - ./_py/ChipFont.py
  - ./_py/ChipDescShort.py
  - ./_py/ChipDescLong.py
  - ./_py/DiceFont.py
  - ./_py/ItemFont.py
  - ./_py/ItemDescFont.py
