language: python

dist: trusty
sudo: false
group: beta

script:
  - /usr/bin/python3 checkjson.py && ./coverage.sh
  - ./tidy-json.sh && git diff --exit-code
  - /usr/bin/python3 dupcheck.py
  - /usr/bin/python3 ItemFont.py json

install:
