language: python
python: 3.6
dist: trusty
sudo: false
group: beta

script:
  - ./checkjson.py && ./coverage.sh
  - ./tidy-json.sh && git diff --exit-code
  - ./dupcheck.py
  - ./ItemFont.py json
  - ./ChipDescShort.py json
  - ./ChipDescLong.py json
